name: CI

on: [push]

jobs:
  show:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1.1.0
    - run: npm install -g esy@0.6.2 --unsafe-perm
    - name: Restore Cache
      id: restore-cache
      uses: actions/cache@v1.1.2
      with:
        path: _export
        key: ${{ runner.os }}-esy-${{ hashFiles('esy.lock/index.json') }}
        restore-keys: |
          ${{ runner-os }}-esy
    - run: 'esy install'
    - name: Import Cache
      run: |
        esy import-dependencies _export
        rm -rf _export
    - run: 'esy'
    - run: |
        esy cleanup .
        esy export-dependencies
      if: steps.restore-cache.outputs.cache-hit != 'true'
    - run: 'esy x repro file.txt'
      working-directory: 'sub/folder'
    - run: 'sed -i "" "s/AAAA/BBBB/g" lib/lib.ml'
    - run: 'esy'
      working-directory: 'sub/folder'
    - run: 'esy x repro file.txt'
      working-directory: 'sub/folder'
